version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nokia_2730
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      API_KEY: "AIzaSyBAnDCX6u1ya5cHQQzN9rQdn43ECzr3pvY"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "Nokia_2730"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    depends_on:
      - postgres
    volumes:
      - ./app:/app

volumes:
  postgres_data:
